[routine]
[[routine.items]]
time_start = "2023-10-01T00:00:00"
time_end = "2025-05-01T20:00:00"
stage_type = "PEACE"
range_start = 0
range_end = 0

[[routine.items]]
time_start = "2025-05-01T20:00:00"
time_end = "2025-05-01T22:00:00"
stage_type = "SHRINK"
range_start = 20000
range_end = 10000

[[routine.items]]
time_start = "2025-05-01T22:00:00"
time_end = "2025-05-02T12:00:00"
stage_type = "PEACE"
range_start = 10000
range_end = 10000

[[routine.items]]
time_start = "2025-05-02T12:00:00"
time_end = "2025-05-02T14:00:00"
stage_type = "SHRINK"
range_start = 10000
range_end = 8000

[[routine.items]]
time_start = "2025-05-02T14:00:00"
time_end = "2025-05-02T18:00:00"
stage_type = "PEACE"
range_start = 8000
range_end = 8000

[[routine.items]]
time_start = "2025-05-02T19:00:00"
time_end = "2025-05-02T22:00:00"
stage_type = "SHRINK"
range_start = 8000
range_end = 4000

[[routine.items]]
time_start = "2025-05-02T22:00:00"
time_end = "2025-05-03T14:00:00"
stage_type = "PEACE"
range_start = 4000
range_end = 4000

[[routine.items]]
time_start = "2025-05-03T14:00:00"
time_end = "2025-05-03T15:00:00"
stage_type = "SHRINK"
range_start = 4000
range_end = 2400

[[routine.items]]
time_start = "2025-05-03T15:00:00"
time_end = "2025-05-03T17:00:00"
stage_type = "PEACE"
range_start = 2400
range_end = 2400

[[routine.items]]
time_start = "2025-05-03T17:00:00"
time_end = "2025-05-03T18:00:00"
stage_type = "SHRINK"
range_start = 2400
range_end = 1000

[[routine.items]]
time_start = "2025-05-03T18:00:00"
time_end = "2025-05-03T19:30:00"
stage_type = "PEACE"
range_start = 1000
range_end = 1000

[[routine.items]]
time_start = "2025-05-03T19:30:00"
time_end = "2025-05-03T20:00:00"
stage_type = "SHRINK"
range_start = 1000
range_end = 400

[[routine.items]]
time_start = "2025-05-03T20:00:00"
time_end = "2025-05-03T20:30:00"
stage_type = "PEACE"
range_start = 400
range_end = 400

[[routine.items]]
time_start = "2025-05-03T20:30:00"
time_end = "2025-05-03T21:30:00"
stage_type = "SHRINK"
range_start = 400
range_end = 0